### ISSUE TITLE
VR headset

### ISSUE THREAD

**Issue by morHalfon** [morHalfon/VR-game-for-driving-lessons#2]
We did a survey to check which VR headset is good for our application: [here]https://drive.google.com/open?id=1WR2Xr7lDQGmPUHqmxQjI6kYmDNB2RW4jr1y86cmlAns)

**Comment by hallel1** [comment]
We chose the virtual reality glasses from the model VR BOX [from here](http://www.vryou.co.il/%D7%9E%D7%A9%D7%A7%D7%A4%D7%99-%D7%9E%D7%A6%D7%99%D7%90%D7%95%D7%AA-%D7%9E%D7%93%D7%95%D7%9E%D7%94-360-%D7%93%D7%92%D7%9D-VR-BOX-20.html)
